# Generated by Django 2.0.6 on 2018-06-19 15:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 страницы')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на страницу')),
                ('replace', models.BooleanField(default=False, verbose_name='Не подменять пустой alias')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст страницы')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Заголовок страницы')),
                ('meta_d', models.CharField(blank=True, max_length=1000, verbose_name='Ключевое описание')),
                ('status', models.BooleanField(default=False, verbose_name='Вкл?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Domain', verbose_name='Домен')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Pages', verbose_name='Родитель')),
            ],
            options={
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=1023, verbose_name='Откуда')),
                ('to', models.CharField(max_length=1023, verbose_name='Куда')),
                ('code', models.CharField(choices=[('0', 301), ('1', 302)], default='0', max_length=255, verbose_name='Код')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
            },
        ),
    ]
