# Generated by Django 2.0.6 on 2018-07-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name=' ')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name=' ')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name=' ')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name=' ')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Домен', 'verbose_name_plural': 'Домены'},
        ),
        migrations.AlterField(
            model_name='pages',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Domain', verbose_name='Домен'),
        ),
    ]
