# Generated by Django 2.0.6 on 2018-07-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180714_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.IntegerField(choices=[(0, 'Сверху'), (1, 'Снизу')], default=0, verbose_name='Расположение')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Соотношение блока и страницы',
                'verbose_name_plural': 'Соотношение блоков и страниц',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Html блок', 'verbose_name_plural': 'Html блоки'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.RemoveField(
            model_name='block',
            name='page',
        ),
        migrations.RemoveField(
            model_name='block',
            name='where',
        ),
        migrations.AddField(
            model_name='pagesblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='pagesblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pages', verbose_name='Страница'),
        ),
    ]
