# Generated by Django 2.0.6 on 2018-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180714_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_link',
            field=models.BooleanField(default=True, verbose_name='Проставлять ссылку?'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Вкл?'),
        ),
    ]
