# Generated by Django 2.0.6 on 2018-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180917_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='template',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кастомный шаблон для поддоменов'),
        ),
    ]
