# Generated by Django 2.0.6 on 2018-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20181001_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Блок на главную',
                'verbose_name_plural': 'Блоки для главной',
            },
        ),
    ]
