# Generated by Django 2.0.6 on 2018-10-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_indexblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblock',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Вкл?'),
        ),
    ]
