# Generated by Django 2.0.6 on 2018-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_indexblock_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexblock',
            options={'ordering': ('order',), 'verbose_name': 'Блок на главную', 'verbose_name_plural': 'Блоки для главной'},
        ),
        migrations.AddField(
            model_name='indexblock',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
