# Generated by Django 2.0.6 on 2018-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20181012_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередность'),
        ),
    ]
