# Generated by Django 2.0.6 on 2018-10-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20181012_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес офиса'),
        ),
    ]
