# Generated by Django 2.0.6 on 2018-12-29 14:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_pages_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['lft'], 'verbose_name_plural': 'Страницы сайта'},
        ),
        migrations.AddField(
            model_name='block',
            name='html_mobile',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Html мобильного блока'),
        ),
    ]
