# Generated by Django 2.0.6 on 2018-12-29 15:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20181229_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesblock',
            name='html_after_block',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Html блока'),
        ),
        migrations.AddField(
            model_name='pagesblock',
            name='html_before_block',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Html блока'),
        ),
    ]
