# Generated by Django 2.0.6 on 2018-12-29 19:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20181229_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesblock',
            name='html_mobile',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Переопределяющий Html мобильного блока'),
        ),
    ]
