# Generated by Django 2.0.6 on 2018-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_pagesblock_html_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesblock',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Очередность'),
        ),
    ]
