# Generated by Django 2.0.6 on 2018-12-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20181229_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesblock',
            name='where',
        ),
    ]
