# Generated by Django 2.0.6 on 2019-08-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_pagesblock_where'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesBlockGrammeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.SmallIntegerField(blank=True, choices=[(0, 'title'), (1, 'desc'), (2, 'h1'), (3, 'name'), (4, 'Галерея'), (5, 'Цены')], verbose_name='Тип блока')),
                ('gramm', models.CharField(blank=True, max_length=255, verbose_name='Грамеммы')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Pages', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Граммема',
                'verbose_name_plural': 'Граммемы',
            },
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Картинка'),
        ),
    ]
