# Generated by Django 2.0.6 on 2019-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_pagesblockgrammeme_prepend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramm', models.CharField(max_length=255, verbose_name='Граммема')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagesblockgrammeme',
            name='gramm',
        ),
        migrations.AddField(
            model_name='pagesblockgrammeme',
            name='gramms',
            field=models.ManyToManyField(to='pages.Grammeme', verbose_name='Граммемы'),
        ),
    ]
