# Generated by Django 2.0.6 on 2019-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_pagesblockgrammeme_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammeme',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название граммемы'),
        ),
    ]
