# Generated by Django 2.0.6 on 2019-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_grammeme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesblockgrammeme',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Подменять?'),
        ),
        migrations.AlterField(
            model_name='pagesblockgrammeme',
            name='prepend',
            field=models.BooleanField(default=False, verbose_name='До?'),
        ),
    ]
