# Generated by Django 2.0.6 on 2019-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20190812_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesblockgrammeme',
            name='transform',
            field=models.IntegerField(choices=[(0, 'Маленькими буквами'), (1, 'С большой буквы'), (2, 'Большими буквами')], default=0, verbose_name='Трансформация текста'),
        ),
    ]
