# Generated by Django 2.0.6 on 2019-08-29 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_pagesblockgrammeme_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 29, 20, 23, 18, 351801), verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления'),
        ),
        migrations.AlterField(
            model_name='pagesblockgrammeme',
            name='active',
            field=models.BooleanField(choices=[(True, 'Подменять'), (False, 'Не подменять')], default=True, verbose_name='Использовать граммему?'),
        ),
        migrations.AlterField(
            model_name='pagesblockgrammeme',
            name='block_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'title'), (1, 'desc'), (3, 'Название в меню'), (4, 'Галерея'), (5, 'Цены')], verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='pagesblockgrammeme',
            name='prepend',
            field=models.BooleanField(choices=[(True, 'В начало'), (False, 'В конец')], default=False, verbose_name='Куда?'),
        ),
    ]
