# Generated by Django 2.0.6 on 2019-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20190829_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='protocol',
            field=models.CharField(blank=True, choices=[('http://', 'http'), ('https://', 'https')], default='http://', max_length=255, verbose_name='Протокол'),
        ),
    ]
